buffy:
  env:
    bot_github_user: <%= ENV['PYOSBOT_GH_USER'] %>
    gh_access_token: <%= ENV['PYOSBOT_GH_ACCESS_TOKEN'] %>
    gh_secret_token: <%= ENV['PYOSBOT_GH_SECRET_TOKEN'] %>
  teams:
    editors: 6762239
  responders:
    help:
    hello:
      hidden: true
    thanks:
      hidden: true
    basic_command:
      - code_of_conduct:
          command: code of conduct
          description: Show our community Code of Conduct and Guidelines
          message: "Here's the pyOpenSci Community Code of Conduct: https://www.pyopensci.org/governance/CODE_OF_CONDUCT"
    list_team_members:
      command: list editors
      team_id: 6762239
      heading: Current pyOpenSci editorial board members
      description: "Get a list of all editors's GitHub handles"
    welcome:
      template_file: welcome_message.md
    label_command:
      only: editors
      command: assign editor
      add_labels:
        - "1/editor-assigned"
      remove_labels:
        - "0/pre-review-checks"
    label_command:
      only: editors
      command: seeking reviewers
      add_labels:
        - "2/seeking-reviewers"
    set_value:
      - version:
          only: editors
          sample_value: "v1.0.0"
      - archive:
          only: editors
          sample_value: "10.5281/zenodo.7158585"
